re-committing reverted commit 3760923f4eff2ae1b3cb2d5f6ad6f39c16af971b after having fixed the compilation error
Testing:
pre-commit http://compute-ci-jenkins.iil.intel.com:8080/job/PRuntimeReport/367/