* Update all headers due to extension spec update. * Fix compilation error in cl.hpp.
Affected projects
=================
* Headers

Relevant Bugs
=============

Reviewers
=========
* Yariv Aridor
* Kipp Owens

http://cvcc-ubu-01.iil.intel.com/cr/r/1910/

Tests
=====
* Jenkins Pre-Commit

http://cvcc-fc14-01.iil.intel.com:8080/job/PersonalRuntimeReport/1174/