Fix warning during build on windows
error: redeclaration of '__tgt_set_info_flag' should not add 'dllexport'
attribute [-Werror,-Wdll-attribute-on-redeclaration]

Change-Id: I52515aeadde989d06f38ffcc07295c53ed63d65e
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/325402
Reviewed-by: Chupin, Pavel V <pavel.v.chupin@intel.com>
Tested-by: Chupin, Pavel V <pavel.v.chupin@intel.com>
(cherry picked from commit c258975f458b0c15fb4a00951f7206f05b0d49fb)
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/325403