Fix build errors due to unsigned/signed comparison. (#11195)
This patch fixes build errors due to unsigned/signed comparison:

/localdisk2/jinsongj/buildbot-test/worker_root/xmain-cand-worker/xmain-cand/xmain-cand/llvm/third-party/unittest/googletest/include/gtest/gtest.h:1526:11: error: comparison of integers of different signs: 'const unsigned int' and 'const int' [-Werror,-Wsign-compare]
 if (lhs == rhs) {
 ~~~ ^ ~~~
/localdisk2/jinsongj/buildbot-test/worker_root/xmain-cand-worker/xmain-cand/xmain-cand/llvm/third-party/unittest/googletest/include/gtest/gtest.h:1553:12: note: in instantiation of function template specialization 'testing::internal::CmpHelperEQ<unsigned int, int>' requested here
 return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
 ^
/localdisk2/jinsongj/buildbot-test/worker_root/xmain-cand-worker/xmain-cand/xmain-cand/llvm/llvm/unittests/Transforms/Vectorize/IntelVPlanValueTrackingTest.cpp:560:7: note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<unsigned int, int, nullptr>' requested here
 EXPECT_EQ(KB.countMinTrailingZeros(), llvm::countr_zero(Step * VF));
 ^
/localdisk2/jinsongj/buildbot-test/worker_root/xmain-cand-worker/xmain-cand/xmain-cand/llvm/third-party/unittest/googletest/include/gtest/gtest.h:2027:54: note: expanded from macro 'EXPECT_EQ'
 EXPECT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)