Fix windows build warnings issues
* SemaSYCL.cpp:
error: moving a local object in a return statement prevents copy elision

Fix upstreamed also at: https://github.com/intel/llvm/pull/3680

* device.cpp:
error: format specifies type 'long' but the argument has type 'int64_t'
(aka 'long long')

Change-Id: I7157a81cdb2975ce489c668d9e2ac8a2a1795b40
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/325480
Reviewed-by: Chupin, Pavel V <pavel.v.chupin@intel.com>
Tested-by: Chupin, Pavel V <pavel.v.chupin@intel.com>
Reviewed-by: Zakharin, Vyacheslav P <vyacheslav.p.zakharin@intel.com>
(cherry picked from commit f9da9127567d9c5de0cc86657ad50a6ffa833e82)
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/325521