Resolve of merge (conflict) 3c9988f85d25 [OpenMP] Allow exceptions in target regions when offloadin.. 'main' -> 'xmain-web' (#15939)
CONFLICT (content): Merge conflict in clang/lib/CodeGen/CGException.cpp

  commit 3c9988f85d2508bdbc64c81fed7c4b9b8db54262
  Author: Anton Rydahl <rydahl2610@gmail.com>
  Date:   Wed Aug 30 09:34:31 2023 -0700

[OpenMP] Allow exceptions in target regions when offloading to GPUs

The motivation for this patch is that many code bases use exception
handling. As GPUs are not expected to support exception handling in the
near future, we can experiment with compiling the code for GPU targets
anyway. This will
      allow us to run the code, as long as no exception is thrown.

      The overall idea is very simple:
- If a throw expression is compiled to AMDGCN or NVPTX, it is replaced
with a trap during code generation.
- If a try/catch statement is compiled to AMDGCN or NVPTX, we generate
code for the try statement as if it were a basic block.

      With this patch, the compilation of the following example
      ```
      int gaussian_sum(int a,int b){
              if ((a + b) % 2 == 0) {throw -1;};
              return (a+b) * ((a+b)/2);
      }

      int main(void) {
              int gauss = 0;
              #pragma omp target map(from:gauss)
              {
                      try {
                              gauss = gaussian_sum(1,100);
                      }
                      catch (int e){
                              gauss = e;
                      }
              }
              std::cout << "GaussianSum(1,100)="<<gauss<<std::endl;
              #pragma omp target map(from:gauss)
              {
                      try {
                              gauss = gaussian_sum(1,101);
                      }
                      catch (int e){
                              gauss = e;
                      }
              }
              std::cout << "GaussianSum(1,101)="<<gauss<<std::endl;
              return (gauss > 1) ? 0 : 1;
      }
      ```
      with offloading to `gfx906` results in
      ```
      ./bin/target_try_minimal_fail
      GaussianSum(1,100)=5050
AMDGPU fatal error 1: Received error in queue 0x155555506000:
HSA_STATUS_ERROR_EXCEPTION: An HSAIL operation resulted in a hardware
exception.
      zsh: abort (core dumped)
      ```

      Reviewed By: jdoerfert

      Differential Revision: https://reviews.llvm.org/D153924

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Tyler Lanphear <tyler.lanphear@intel.com>