Resolve of merge (conflict) 3ddc88c38068 Revert "[AST] Use ModRefInfo to represent access kind (NFC)" 'main' -> 'xmain-web' (#11657)
* Resolve of merge (conflict) 3ddc88c38068 Revert "[AST] Use ModRefInfo to represent access kind (NFC)" 'main' -> 'xmain-web'

  CONFLICT (content): Merge conflict in llvm/include/llvm/Analysis/AliasSetTracker.h

  commit 3ddc88c38068449842b5ae31285d2a194f0dc4f9
  Author: Nikita Popov <npopov@redhat.com>
  Date:   Fri Mar 17 17:22:37 2023 +0100

      Revert "[AST] Use ModRefInfo to represent access kind (NFC)"

      This reverts commit 2c78a9e65ccfe36d213a409592bebdd3ed8ba771.

      Fails to compile on mlir-s390x-linux buildbot using GCC 9.4 with:

          llvm/lib/Analysis/AliasSetTracker.cpp: In member function 'void llvm::AliasSet::mergeSetIn(llvm::AliasSet&, llvm::AliasSetTracker&, llvm::BatchAAResults&)':
          llvm/lib/Analysis/AliasSetTracker.cpp:50:19: error: invalid operands of types 'unsigned char:2' and 'unsigned char:2' to binary 'operator|'

* conflict resolution

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Manna, Soumi <soumi.manna@intel.com>