Resolve of merge (conflict) 26eec9e9dbc2 Revert "[clang] Implement Change scope of lambda trailing-.. 'main' -> 'xmain-web' (#4414)
* Resolve of merge (conflict) 26eec9e9dbc2 Revert "[clang] Implement Change scope of lambda trailing-.. 'main' -> 'xmain-web'

  CONFLICT (content): Merge conflict in clang/include/clang/Sema/Scope.h

  commit 26eec9e9dbc20186f6b810fe01d3a01aac8ae6f4
  Author: Mehdi Amini <joker.eph@gmail.com>
  Date:   Wed Apr 13 19:34:21 2022 +0000

      Revert "[clang] Implement Change scope of lambda trailing-return-type"

      This reverts commit adff142dc253d65b6560e420bba6b858d88d4a98.
      This broke clang bootstrap: it made existing C++ code in LLVM invalid:

      llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
                    [=](std::remove_reference_t<decltype(*Idx)> V,
                                                          ^

* conflict resolution

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Soumi Manna <soumi.manna@intel.com>