[Xmain-web] Fix build error with unused variable 'Ctx' when -werror=on (#4091)
This patch fixes build error on xmain-web when -werror=on:

/localdisk2/smanna/Sandbox/xmain-web1/llvm/clang/lib/CodeGen/CodeGenAction.cpp:321:20: error: unused variable 'Ctx' [-Werror,-Wunused-variable]
      LLVMContext &Ctx = getModule()->getContext();
                   ^
1 error generated.