Resolve of merge (conflict) dc900eeaf2af [test] Fix threadlocal_address.cpp after D129833 'main' -> 'xmain-web' (#6470)
  CONFLICT (content): Merge conflict in clang/test/CodeGenCXX/threadlocal_address.cpp

  commit dc900eeaf2af0d459c69224b2d023d8d2287944a
  Author: Fangrui Song <i@maskray.me>
  Date:   Sun Jul 31 23:49:33 2022 -0700

      [test] Fix threadlocal_address.cpp after D129833

      Older Darwin does not support thread_local:

      error: thread-local storage is not supported for the current target
        thread_local int j = 0;

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Maosu Zhao <maosu.zhao@intel.com>