CMPLRLLVM-52200: Update PrintIR API name due to c718336c4cb1 (#16638)
Fix build failures in release build.

> ERROR with results from task:
> Task: #5 (2023-10-01 18:31:24): Linux EFI2 release [release
-wslog=builds/build.log -bldocl -werror=off]
[lx_xmain_release_xmainefi2linux.2]
> 
> Scratch directory:
/home/cmplr/scrna15/scr/sys_iclsrc/9c/scsel-icx-07_latest-buildable/lx_xmain_release_xmainefi2linux.2
> ERROR# U61 (2023-10-01 18:30:00): system=scvnbux052 : Build error: See
details in 'warning.log' file, more info in
alloy/results/lx_xmain_release_xmainefi2linux.2/build*.log and full info
in
/nfs/sc/proj/icl/scrna15/scr/sys_iclsrc/9c/scsel-icx-07_latest-buildable/lx_xmain_release_xmainefi2linux.2/spool/nblog2.log
>
file:////scssgfiler01.sc.intel.com/scrna15/scr/sys_iclsrc/9c/scsel-icx-07_latest-buildable/lx_xmain_release_xmainefi2linux.2/
>
file:////scssgfiler01.sc.intel.com/scrna15/scr/sys_iclsrc/9c/scsel-icx-07_latest-buildable/lx_xmain_release_xmainefi2linux.2/spool/nblog2.log
> 
> nblog2.log: 43153: [ 76%] Building CXX object
lib/Passes/CMakeFiles/LLVMPasses.dir/StandardInstrumentations.cpp.o
> nblog2.log: 43154:
/netbatch/build_comp2184517_00/ics_top/llvm/llvm/lib/Passes/StandardInstrumentations.cpp:1055:30:
error: out-of-line definition of 'pushModuleDesc' does not match any
declaration in 'llvm::PrintIRInstrumentation'
> nblog2.log: 43155: void
PrintIRInstrumentation::pushModuleDesc(StringRef, Any) {}
> nblog2.log: 43156:                              ^~~~~~~~~~~~~~
> nblog2.log: ...
> nblog2.log: 43161: make[2]: ***
[lib/Passes/CMakeFiles/LLVMPasses.dir/StandardInstrumentations.cpp.o]
Error 1