Resolve of merge (conflict) 5ff27fe1ff03 [clang-repl] Recover the lookup tables of the primary cont.. 'main' -> 'xmain-web' (1 commits) (#5303)
* Resolve of merge (conflict) 5ff27fe1ff03 [clang-repl] Recover the lookup tables of the primary cont.. 'main' -> 'xmain-web' (1 commits)

  CONFLICT (content): Merge conflict in clang/test/Interpreter/execute.cpp

  commit 5ff27fe1ff03d5aeaf8567c97618170f0cef8f58
  Author: Purva-Chaudhari <purva.chaudhari02@gmail.com>
  Date:   Sun May 29 04:55:10 2022 +0000

      [clang-repl] Recover the lookup tables of the primary context.

      Before this patch, there was re-declaration error if error was encountered in
      the same line. The recovery support acted only if this type of error was
      encountered in the first line of the program and not in subsequent lines.

      For example:

      ```
      clang-repl> int i=9;
      clang-repl> int j=9; err;
      input_line_3:1:5: error: redefinition of 'j'
      int j = 9;
      ```

      Differential revision: https://reviews.llvm.org/D123674

* conflict resolution

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Soumi Manna <soumi.manna@intel.com>