Resolve of merge (conflict) 29b6e967f3e9 Revert "[InferAttrs] Add writeonly to all the math functio.. '"main"' -> '"xmain-web"' (#2215)
* Resolve of merge (conflict) 29b6e967f3e9 Revert "[InferAttrs] Add writeonly to all the math functio.. '"main"' -> '"xmain-web"'

  CONFLICT (content): Merge conflict in llvm/test/Transforms/InferFunctionAttrs/annotate.ll

  commit 29b6e967f3e99ac45340ea37a70262c70e4e7528
  Author: Martin Storsjö <martin@martin.st>
  Date:   Wed Jan 5 10:54:07 2022 +0200

      Revert "[InferAttrs] Add writeonly to all the math functions"

      This reverts commit ea75be3d9df448b6abafaf752a8141764d93ca33 and
      1eb5b6e85045d22720f177a02aaf7097930e4b4f.

      That commit caused crashes with compilation e.g. like this
      (not fixed by the follow-up commit):

      $ cat sqrt.c
      float a;
      b() { sqrt(a); }
      $ clang -target x86_64-linux-gnu -c -O2 sqrt.c
      Attributes 'readnone and writeonly' are incompatible!
        %sqrtf = tail call float @sqrtf(float %0) #1
      in function b
      fatal error: error in backend: Broken function found, compilation aborted!

* Resolving conflicts

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Ivan Kelarev <ivan.kelarev@intel.com>