[Xmain-web][LIT] Fix failed tests with misspelled directive errors (#5268)
This patch fixes the tests that fail due to https://reviews.llvm.org/D125604 with errors like:
error: misspelled directive 'CHECK_SAME:'
error: misspelled directive 'CHECK_NEXT:'
error: misspelled directive 'CHECK_NOT:'

Fixes 24 LIT tests failures on xmain-web.