Resolve of merge (conflict) cb03b1bd9931 Revert "[IPSCCP] Move the IPSCCP run function under the IP.. 'main' -> 'xmain-web' (1 commits) (#9300)
* Resolve of merge (conflict) cb03b1bd9931 Revert "[IPSCCP] Move the IPSCCP run function under the IP.. 'main' -> 'xmain-web' (1 commits)

  CONFLICT (content): Merge conflict in llvm/lib/Transforms/Utils/SCCPSolver.cpp
  CONFLICT (content): Merge conflict in llvm/lib/Transforms/Scalar/SCCP.cpp
  CONFLICT (content): Merge conflict in llvm/lib/Transforms/IPO/SCCP.cpp
  CONFLICT (content): Merge conflict in llvm/lib/Transforms/IPO/CMakeLists.txt

  commit cb03b1bd99313a728d47060b909a73e7f5991231
  Author: Alexandros Lamprineas <alexandros.lamprineas@arm.com>
  Date:   Thu Dec 8 12:42:34 2022 +0000

      Revert "[IPSCCP] Move the IPSCCP run function under the IPO directory."

      This reverts commit 42c2dc401742266da3e0251b6c1ca491f4779963.

      This broke some buildbots:

       undefined reference to `llvm::createBitTrackingDCEPass()'
       undefined reference to `llvm::createAlignmentFromAssumptionsPass()'
       undefined reference to `llvm::createLoopUnrollPass(int, bool, bool, int, int, int, int, int, int)'
       undefined reference to `llvm::createLICMPass(unsigned int, unsigned int, bool)'
       undefined reference to `llvm::createWarnMissedTransformationsPass()'
       undefined reference to `llvm::createAlignmentFromAssumptionsPass()'
       undefined reference to `llvm::createCallSiteSplittingPass()'
       undefined reference to `llvm::createCFGSimplificationPass(llvm::SimplifyCFGOptions, std::function<bool (llvm::Function const&)>)'
       undefined reference to `llvm::createFloat2IntPass()'
       undefined reference to `llvm::createLowerConstantIntrinsicsPass()'
       undefined reference to `llvm::createLoopRotatePass(int, bool)'
       undefined reference to `llvm::createLoopDistributePass()'
       undefined reference to `llvm::createLoopSinkPass()'
       undefined reference to `llvm::createInstSimplifyLegacyPass()'
       undefined reference to `llvm::createDivRemPairsPass()'
       undefined reference to `llvm::createCFGSimplificationPass(llvm::SimplifyCFGOptions, std::function<bool (llvm::Function const&)>)'
       undefined reference to `llvm::SetLicmMssaOptCap'
       undefined reference to `llvm::SetLicmMssaNoAccForPromotionCap'
       undefined reference to `llvm::ForgetSCEVInLoopUnroll'

* Resolved conflicts

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Ernesto Su <ernesto.su@intel.com>