CMPLRLLVM-53310: Use unsigned int in constexpr to avoid ambiguous call
On windows ICX build , using int may cause build failures.

clang-offload-wrapper/SymPropReader.cpp(168,34): error: call to member
function 'getAggregateElement' is ambiguous

Cherry-pick of https://github.com/intel/llvm/pull/11776