Refine Resolve of merge (conflict) 7c78cb4b1f49 Revert "[SimplifyCFG][LICM] Preserve nonnull, range and al.. 'main' -> 'xmain-web' #12128 (#12202)
This fixed build error under release config:

/netbatch/build_comp455411_00/ics_top/llvm/llvm/lib/Transforms/Scalar/LICM.cpp:1807:18: error: unused variable 'KnownIDs' [-Werror,-Wunused-variable]
const unsigned KnownIDs[] = {LLVMContext::MD_std_container_ptr,