[VPlan][LLVM IR CG] GEP re-vectorization fixes
Note that

  %gep = getelementptr i8, <2 x i8*> %ptr, <4 x i32><i32 0, i32 1, i32 3, i32 7>

isn't a valid IR:

  error: getelementptr vector index has a wrong number of elements

so we have to ensure all the operands are widened to the same number of elements
in their vector types.

Change-Id: I3bb0c60a32303f2c36429548a000712a6515b720
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/265042
Reviewed-by: Elovikov, Andrei <andrei.elovikov@intel.com>
Tested-by: Elovikov, Andrei <andrei.elovikov@intel.com>