Revert "Enable Infer AS"
This reverts commit 516b6c1827043202d053968cebb35efc780e4109.

"wait_group_events" built-in is not supported. It caused some tests to fail with:
Device build started
Failed to build device program
Error: unimplemented function(s) used:
_Z17wait_group_eventsiPU3AS49ocl_event is undefined 
CompilerException Failed to parse IR

Need to add support for mentioned built-in.

Change-Id: Id00dd47dc3ff2240396cb15ed3b86bd2b91b9eed
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/189738
Reviewed-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>
Tested-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>