Fix for CMPLRLLVM-9589. This patch is to fix a set of errors that are generated during the xmain build on RH7 and RH8 with gcc 8.2.0 prod version: ics set config -ws xmainefi2linux prod gcc=8.2.0 binutils=sys
Erich can you please take a look at the changes I have made.
Sometimes I have added a -Wno warning and sometimes I edited the code.
If you think the change from strncp to memcpy is too expensive we can keep
the strncp and add an explicit '\0 to the end of the string.

Since the build seems to be stopping at the first error (even with -ignore option), I have gathered the errors in a list.
Let me know what if you want to know what patches were necessary for each build error.
So here is the list of errors that I tried to fix with the patch:
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/IR/Core.cpp:89:18: err\
or: cast between incompatible function types from ‘LLVMDiagnosticHandler’ {aka \
‘void (*)(LLVMOpaqueDiagnosticInfo*, void*)’} to ‘llvm::DiagnosticHandler::Diag\
nosticHandlerTy’ {aka ‘void (*)(const llvm::DiagnosticInfo&, void*)’} [-Werror=\
cast-function-type]
           Handler),
                  ^
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/IR/Core.cpp: In functi\
on ‘void (* LLVMContextGetDiagnosticHandler(LLVMContextRef))(LLVMDiagnosticInfo\
Ref, void*)’:
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/IR/Core.cpp:95:48: err\
or: cast between incompatible function types from ‘llvm::DiagnosticHandler::Dia\
gnosticHandlerTy’ {aka ‘void (*)(const llvm::DiagnosticInfo&, void*)’} to ‘LLVM\
DiagnosticHandler’ {aka ‘void (*)(LLVMOpaqueDiagnosticInfo*, void*)’} [-Werror=\
cast-function-type]
       unwrap(C)->getDiagnosticHandlerCallBack());
                                                ^
-------
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/IR/Instruction.cpp: In\
 member function ‘void llvm::Instruction::copyMetadata(const llvm::Instruction&\
, llvm::ArrayRef<unsigned int>)’:
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/IR/Instruction.cpp:782\
:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (WL.empty() || WLS.count(MD.first))
     ^~
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/IR/Instruction.cpp:790\
:7: note: ...this statement, but the latter is misleadingly indented as if it w\
ere guarded by the ‘if’
       if (MD.second != MDIR)
       ^~
----
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/Object/WindowsResource\
.cpp:537:10: error: ‘char* strncpy(char*, const char*, size_t)’ output truncate\
d before terminating nul copying 8 bytes from a string of the same length [-Wer\
ror=stringop-truncation]
   strncpy(SectionOneHeader->Name, ".rsrc$01", (size_t)COFF::NameSize);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

----
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/Transforms/Intel_LoopT\
ransforms/HIRUnrollAndJam.cpp:469:6: error: ‘bool {anonymous}::HIRUnrollAndJam:\
:isUninitialized(llvm::loopopt::HLLoop*) const’ defined but not used [-Werror=u\
nused-function]
 bool HIRUnrollAndJam::isUninitialized(HLLoop *Lp) const {
      ^~~~~~~~~~~~~~~

----
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/Analysis/Intel_Anderse\
ns.cpp:165:20: error: unnecessary parentheses in declaration of ‘Andersens_Allo\
c_Intrinsics’ [-Werror=parentheses]
 static const char *(Andersens_Alloc_Intrinsics[]) = {
                    ^
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/Analysis/Intel_Anderse\
ns.cpp:218:20: error: unnecessary parentheses in declaration of ‘Andersens_No_S\
ide_Effects_Intrinsics’ [-Werror=parentheses]
 static const char *(Andersens_No_Side_Effects_Intrinsics[]) = {
                    ^
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/Analysis/Intel_Anderse\
ns.cpp:252:20: error: unnecessary parentheses in declaration of ‘Andersens_Memc\
py_Intrinsics’ [-Werror=parentheses]
 static const char *(Andersens_Memcpy_Intrinsics[]) = {

/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/tools/clang/include/clang/\
Sema/Overload.h:750:10: error: ‘<anonymous>.clang::OverloadCandidate::Function’\
 is used uninitialized in this function [-Werror=uninitialized]
   struct OverloadCandidate {
          ^~~~~~~~~~~~~~~~~
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/tools/clang/include/clang/\
Sema/Overload.h:750:10: error: ‘<anonymous>.clang::OverloadCandidate::FoundDecl\
’ is used uninitialized in this function [-Werror=uninitialized]
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/tools/clang/include/clang/\
Sema/Overload.h:750:10: error: ‘<anonymous>.clang::OverloadCandidate::Surrogate\
’ is used uninitialized in this function [-Werror=uninitialized]
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/tools/clang/include/clang/\
Sema/Overload.h:750:10: error: ‘<anonymous>.clang::OverloadCandidate::FailureKi\
nd’ is used uninitialized in this function [-Werror=uninitialized]
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/tools/clang/include/clang/\
Sema/Overload.h:750:10: error: ‘<anonymous>.clang::OverloadCandidate::ExplicitC\
allArguments’ is used uninitialized in this function [-Werror=uninitialized]
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/tools/clang/include/clang/\
Sema/Overload.h:750:10: error: ‘<anonymous>.clang::OverloadCandidate::<anonymou\
s>’ is used uninitialized in this function [-Werror=uninitialized]
[ 85%] Building CXX object tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/Se\
maTemplate.cpp.o

----
/export/iusers/zahiraam/xmain_ws/xmain_jira9589/llvm/lib/Transforms/Vectorize/I\
ntel_VPlan/IntelVPlanHCFGBuilder.cpp:1904:6: error: ‘bool {anonymous}::PlainCFG\
Builder::isExternalDef(llvm::Value*) const’ defined but not used [-Werror=unuse\
d-function]
 bool PlainCFGBuilder::isExternalDef(Value *Val) const {
      ^~~~~~~~~~~~~~~

Change-Id: I38f45586ef2576e954a8e9c8d0d5f962eec03306
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/197176
Reviewed-by: Ammarguellat, Zahira <zahira.ammarguellat@intel.com>
Tested-by: Ammarguellat, Zahira <zahira.ammarguellat@intel.com>
Old/split llvm commit ID: 071b25a5606912f727061e3f35b155f010d35842