Resolve build failures in xmainoclefi2win library: warning turned into errors for TR1 usgage
This addresses errors seen of the form:
    87>d:\netbatch\build_comp85308_00\ics_top\llvm\projects\opencl\externals\gtest\googletest\include\gtest\internal\gte
    st-port.h(996): error C2220: warning treated as error - no 'object'
    file generated [D:\netbatch\build_comp85308_00\ics_top\builds\xmainoclx86win_release\llvm\projects\opencl\externals\gtest\googlemock\gmock.vcxproj]
        87>d:\netbatch\build_comp85308_00\ics_top\llvm\projects\opencl\externals\gtest\googletest\include\gtest\internal\gtest-port.h(996): warning C4996: 'std::tr1': warning STL4002: The
	non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define
	_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.
	[D:\netbatch\build_comp85308_00\ics_top\builds\xmainoclx86win_release\llvm\projects\opencl\externals\gtest\googlemock\gmock.vcxproj]

Change-Id: I28fcab5c129b7e2d891747af376d8df9119da3e6
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/175251
Reviewed-by: Savonichev, Andrew <andrew.savonichev@intel.com>
Tested-by: Rao, Premanand M <premanand.m.rao@intel.com>
(cherry picked from commit cee19caf7c005fece865b343c7074e34161809a8)
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/175639
Reviewed-by: Andrews, Elizabeth <elizabeth.andrews@intel.com>
Tested-by: Andrews, Elizabeth <elizabeth.andrews@intel.com>