Resolve of merge (conflict) 74ce297045ba Revert "[Clang] Implement Change scope of lambda trailing-.. 'main' -> 'xmain-web' (#10847)
* Resolve of merge (conflict) 74ce297045ba Revert "[Clang] Implement Change scope of lambda trailing-.. 'main' -> 'xmain-web'

  CONFLICT (content): Merge conflict in clang/include/clang/Sema/Scope.h

  commit 74ce297045bac4bc475b8e762d2a1ea19bb16d3c
  Author: Jordan Rupprecht <rupprecht@google.com>
  Date:   Fri Feb 3 08:49:34 2023 -0800

      Revert "[Clang] Implement Change scope of lambda trailing-return-type"

      This reverts commit d708a186b6a9b050d09558163dd353d9f738c82d (and typo fix e4bc9898ddbeb70bc49d713bbf863f050f21e03f). It causes a compilation error for this:

      ```
      struct StringLiteral {
        template <int N>
        StringLiteral(const char (&array)[N])
            __attribute__((enable_if(N > 0 && N == __builtin_strlen(array) + 1,
                                     "invalid string literal")));
      };

      struct Message {
        Message(StringLiteral);
      };

      void Func1() {
        auto x = Message("x");  // Note: this is fine

        // Note: "xx\0" to force a different type, StringLiteral<3>, otherwise this
        // successfully builds.
        auto y = [&](decltype(Message("xx"))) {};

        // ^ fails with: repro.cc:18:13: error: reference to local variable 'array'
        // declared in enclosing function 'StringLiteral::StringLiteral<3>'

        (void)x;
        (void)y;
      }
      ```

      More details posted to D124351.

* resolution

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: KornevNikita <nikita.kornev@intel.com>