// INTEL_FEATURE_ISA_FP16 [CMPLRLLVM-20842] Fix the regression bug below:
fatal error: error in backend: Cannot select: t99: v16f32 = uint_to_fp t98
  t98: v16i16,ch = load<(dereferenceable load 32 from %ir.29)> t94, t128, undef:i64

Even if target supports feature FP16, i16 to f32/f64 converting is still
illegal.

PS. We don't need extera tests, because tests in CodeGen/X86/vec_int_to_fp.ll
like sitofp_8i16_to_8f32 etc. can cover these cases.
// end INTEL_FEATURE_ISA_FP16

Change-Id: If71ff6bde609ba46ad127e817d2ba2e15f68af6b
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/256851
Reviewed-by: Pengfei Wang <pengfei.wang@intel.com>
Tested-by: Pengfei Wang <pengfei.wang@intel.com>
Reviewed-by: Dai, Chunyang <chunyang.dai@intel.com>