[xmain-web] Fix failing paralel_offloading_map.c
Failed like this:

  error: variable-sized object may not be initialized

Probably caused by https://reviews.llvm.org/D89523:

  552c6c232872 | PR44406: Follow behavior of array bound constant folding in
  more recent versions of GCC.

And see a similar fix (https://github.com/llvm/llvm-project/commit/efd02c1548ee)
in the community as a follow-up to the previously mentioned commit:

  efd02c1548ee | Fix accidental use of VLAs that causes these tests to fail
  after Clang commit 552c6c2328723a248c2b4d2765f75d49129dff20.

Change-Id: Icea5c9ac4ea0e2f6c23517dc5557ce12234286d6
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/278666
Reviewed-by: Elovikov, Andrei <andrei.elovikov@intel.com>
Tested-by: Elovikov, Andrei <andrei.elovikov@intel.com>