Resolve of merge (conflict) 1495d51ee9e7 [lit] Drop "Script:", make -v and -a imply -vv 'main' -> 'xmain-web' (#16370)
CONFLICT (content): Merge conflict in llvm/utils/lit/lit/LitConfig.py
  CONFLICT (content): Merge conflict in llvm/utils/lit/lit/main.py

  commit 1495d51ee9e71fa58b523ec1703b3e258283481f
  Author: Joel E. Denny <jdenny.ornl@gmail.com>
  Date:   Tue Sep 19 12:36:52 2023 -0400

      [lit] Drop "Script:", make -v and -a imply -vv

      This patch and D156954 were discussed in
<https://discourse.llvm.org/t/rfc-improving-lits-debug-output/72839>.

**Motivation**: -a shows output from all tests, and -v shows output
      from just failed tests.  Without this patch, that output from each
      test includes a section called "Script:", which includes all shell
commands that lit has computed from RUN directives and will attempt to
      run for that test.  The effect of -vv (which also implies -v if
      neither -a or -v is specified) is to extend that output with shell
commands as they are executing so you can easily see which one failed.

      For example, when using lit's internal shell and -vv:

      ```
      Script:
      --
      : 'RUN: at line 1'; echo hello world
      : 'RUN: at line 2'; 3c40 hello world
      : 'RUN: at line 3'; echo hello world
      --
      Exit Code: 127

      Command Output (stdout):
      --
      $ ":" "RUN: at line 1"
      $ "echo" "hello" "world"
      hello world

      $ ":" "RUN: at line 2"
      $ "3c40" "hello" "world"
      '3c40': command not found
      error: command failed with exit status: 127

      --
      ```

      Notice that all shell commands that actually execute appear in the
      output twice, once for "Script:" and once for -vv.  Especially for
tests with many RUN directives, the result is noisy. When searching
through the output for a particular shell command, it is easy to get
      lost and mistake shell commands under "Script:" for shell commands
      that actually executed.

      **Change**: With this patch, a test's output changes in two ways.
First, the "Script:" section is never shown. Second, omitting -vv no
longer disables printing of shell commands as they execute. That is,
-a and -v imply -vv, and so -vv is deprecated as it is just an alias
      for -v.

**Secondary motivation**: We are also working to introduce a PYTHON
directive, which can appear between RUN directives. How should PYTHON
      directives be represented in the "Script:" section, which has
      previously been just a shell script?  We could probably think of
something, but adding info about PYTHON directive execution in the -vv
      trace seems more straight-forward and more useful.

(This patch also removes a confusing point in the -vv documentation:
at least when using bash as an external shell, -vv echoes commands to
      the shell's stderr not stdout.)

      Reviewed By: awarzynski, Endill, ldionne, MaskRay

      Differential Revision: https://reviews.llvm.org/D154984

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Tyler Lanphear <tyler.lanphear@intel.com>