Resolve of merge (conflict) 883dbb9c86be Revert "[MemProf] Context disambiguation cloning pass [pat.. 'main' -> 'xmain-web' (#11796)
* Resolve of merge (conflict) 883dbb9c86be Revert "[MemProf] Context disambiguation cloning pass [pat.. 'main' -> 'xmain-web'

  CONFLICT (content): Merge conflict in llvm/lib/Passes/PassBuilderPipelines.cpp

  commit 883dbb9c86be87593a58ef10b070b3a0564c7fee
  Author: Nikita Popov <npopov@redhat.com>
  Date:   Wed Mar 22 15:43:46 2023 +0100

      Revert "[MemProf] Context disambiguation cloning pass [patch 1a/3]"

      This reverts commit d6ad4f01c3dafcab335bca66dac6e36d9eac8421.

      Fails to build on at least gcc 12.2:

      /home/npopov/repos/llvm-project/llvm/lib/Transforms/IPO/MemProfContextDisambiguation.cpp:482:1: error: no declaration matches ‘ContextNode<DerivedCCG, FuncTy, CallTy>* CallsiteContextGraph<DerivedCCG, FuncTy, CallTy>::getNodeForInst(const CallInfo&)’
        482 | CallsiteContextGraph<DerivedCCG, FuncTy, CallTy>::getNodeForInst(
            | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /home/npopov/repos/llvm-project/llvm/lib/Transforms/IPO/MemProfContextDisambiguation.cpp:393:16: note: candidate is: ‘CallsiteContextGraph<DerivedCCG, FuncTy, CallTy>::ContextNode* CallsiteContextGraph<DerivedCCG, FuncTy, CallTy>::getNodeForInst(const CallInfo&)’
        393 |   ContextNode *getNodeForInst(const CallInfo &C);
            |                ^~~~~~~~~~~~~~
      /home/npopov/repos/llvm-project/llvm/lib/Transforms/IPO/MemProfContextDisambiguation.cpp:99:7: note: ‘class CallsiteContextGraph<DerivedCCG, FuncTy, CallTy>’ defined here
         99 | class CallsiteContextGraph {
            |       ^~~~~~~~~~~~~~~~~~~~

* conflict resolution

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Manna, Soumi <soumi.manna@intel.com>