Fix build errors due to change of getFixedSize() to getFixedValue() and 'unsigned' -> Align community move for DataLayout (#10519) (#10655)
This patch fixes three build errors:

use getFixedValue() instead of getFixedSize()
'getPrefTypeAlignment' is deprecated: use getPrefTypeAlign instead
The alignment is now returned not as ‘unsigned’ but ‘Align’ wrapper
Fixes the build error If i use getPrefTypeAlign instead:
Example:
lib/Transforms/ReorderFields.cpp:1628:13: error: no viable conversion from 'Align' to 'uint64_t' (aka 'unsigned long')
FD0.set(DL.getABITypeAlign(Ty0), DL.getTypeStoreSize(Ty0), 0,
^~~~~~~~~~~~~~~~~~~~~~~