[debugger]: make the gdb script Python 3 compatible
On Ubuntu 16.04 gdb uses Python 3.5.2 whereas on other systems
e.g. CentOS 7.3, the stock gdb uses Python 2.7.5.

When trying to source the file there is a syntax error:

(gdb) source /tmp/libintelocl.so-gdb.py
  File "/tmp/libintelocl.so-gdb.py", line 22
    print "WARNING: Unable to set OpenCL breakpoint at location " \
                                                                ^
SyntaxError: Missing parentheses in call to 'print'
(gdb)