Fix libomptarget build on Windows
Build failed with:

openmp\libomptarget\src\private.h(130): error C2220: warning treated as error - no 'object' file generated
openmp\libomptarget\src\private.h(130): warning C4477: 'fprintf' : format string '%-8ld' requires an argument of type 'long', but variadic argument 6 has type 'uint64_t'
openmp\libomptarget\src\private.h(130): note: consider using '%lld' in the format string
openmp\libomptarget\src\private.h(130): note: consider using '%Id' in the format string
openmp\libomptarget\src\private.h(130): note: consider using '%I64d' in the format string

Change-Id: Idfd3597989fa6c5f236e82cc9c2cdb8bd350671f
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/308533
Reviewed-by: Sachkov, Alexey <alexey.sachkov@intel.com>
Tested-by: Sachkov, Alexey <alexey.sachkov@intel.com>