Fix build errors due to deprecated declarations (#11186)
This patch resolves build errors below with option -werror=on:

/llvm/opencl-intel/FrontendDriver/ParseSPIRV.cpp:52:44: error: 'ByteSwap_32' is deprecated: use llvm::byteswap instead [-Werror,-Wdeprecated-declarations]
  return m_littleEndian ? *wordPtr : llvm::ByteSwap_32(*wordPtr);
                                           ^~~~~~~~~~~
                                           llvm::byteswap
/llvm/llvm/include/llvm/Support/SwapByteOrder.h:55:1: note: 'ByteSwap_32' has been explicitly marked deprecated here
LLVM_DEPRECATED("use llvm::byteswap instead", "llvm::byteswap")
^
/llvm/llvm/include/llvm/Support/Compiler.h:143:50: note: expanded from macro 'LLVM_DEPRECATED'
#define LLVM_DEPRECATED(MSG, FIX) __attribute__((deprecated(MSG, FIX)))
                                                 ^
/llvm/opencl-intel/FrontendDriver/ParseSPIRV.cpp:62:36: error: 'ByteSwap_32' is deprecated: use llvm::byteswap instead [-Werror,-Wdeprecated-declarations]
         spv::MagicNumber == llvm::ByteSwap_32(Magic);
                                   ^~~~~~~~~~~
                                   llvm::byteswap
/llvm/llvm/include/llvm/Support/SwapByteOrder.h:55:1: note: 'ByteSwap_32' has been explicitly marked deprecated here
LLVM_DEPRECATED("use llvm::byteswap instead", "llvm::byteswap")
^
/llvm/llvm/include/llvm/Support/Compiler.h:143:50: note: expanded from macro 'LLVM_DEPRECATED'
#define LLVM_DEPRECATED(MSG, FIX) __attribute__((deprecated(MSG, FIX)))
                                                 ^
2 errors generated.

/llvm/llvm/Intel_OptionalComponents/DTrans/lib/Analysis/DTransUtils.cpp:445:10: error: 'countPopulation<unsigned long>' is deprecated: Use llvm::popcount instead. [-Werror,-Wdeprecated-declarations]
  assert(countPopulation(SafetyInfo) == 1 &&
         ^
/llvm/llvm/include/llvm/Support/MathExtras.h:335:1: note: 'countPopulation<unsigned long>' has been explicitly marked deprecated here
LLVM_DEPRECATED("Use llvm::popcount instead.", "llvm::popcount")
^
/llvm/llvm/include/llvm/Support/Compiler.h:143:50: note: expanded from macro 'LLVM_DEPRECATED'
#define LLVM_DEPRECATED(MSG, FIX) __attribute__((deprecated(MSG, FIX)))
                                                 ^
1 error generated.

/llvm/llvm/lib/Transforms/Vectorize/Intel_VPlan/IntelVPOCodeGen.cpp:4667:32: error: 'PowerOf2Floor' is deprecated: use llvm::bit_floor instead [-Werror,-Wdeprecated-declarations]
  unsigned FinalLoopVF = llvm::PowerOf2Floor(NumElems);
                               ^~~~~~~~~~~~~
                               llvm::bit_floor
/llvm/llvm/include/llvm/Support/MathExtras.h:462:1: note: 'PowerOf2Floor' has been explicitly marked deprecated here
LLVM_DEPRECATED("use llvm::bit_floor instead", "llvm::bit_floor")
^
/llvm/llvm/include/llvm/Support/Compiler.h:143:50: note: expanded from macro 'LLVM_DEPRECATED'
#define LLVM_DEPRECATED(MSG, FIX) __attribute__((deprecated(MSG, FIX)))
                                                 ^
1 error generated.

/llvm/llvm/lib/Transforms/Vectorize/Intel_VPlan/VPlanHIR/IntelVPOCodeGenHIR.cpp:4350:34: error: 'PowerOf2Floor' is deprecated: use llvm::bit_floor instead [-Werror,-Wdeprecated-declarations]
    unsigned FinalLoopVF = llvm::PowerOf2Floor(NumElems);
                                 ^~~~~~~~~~~~~
                                 llvm::bit_floor
/llvm/llvm/include/llvm/Support/MathExtras.h:462:1: note: 'PowerOf2Floor' has been explicitly marked deprecated here
LLVM_DEPRECATED("use llvm::bit_floor instead", "llvm::bit_floor")
^
/llvm/llvm/include/llvm/Support/Compiler.h:143:50: note: expanded from macro 'LLVM_DEPRECATED'
#define LLVM_DEPRECATED(MSG, FIX) __attribute__((deprecated(MSG, FIX)))
                                                 ^
1 error generated.

/llvm/llvm/lib/Transforms/Vectorize/Intel_VPlan/IntelLoopVectorizationPlanner.cpp:414:25: error: 'PowerOf2Floor' is deprecated: use llvm::bit_floor instead [-Werror,-Wdeprecated-declarations]
    Safelen = (unsigned)PowerOf2Floor(Safelen);
                        ^~~~~~~~~~~~~
                        llvm::bit_floor
/llvm/llvm/include/llvm/Support/MathExtras.h:462:1: note: 'PowerOf2Floor' has been explicitly marked deprecated here
LLVM_DEPRECATED("use llvm::bit_floor instead", "llvm::bit_floor")
^
/llvm/llvm/include/llvm/Support/Compiler.h:143:50: note: expanded from macro 'LLVM_DEPRECATED'
#define LLVM_DEPRECATED(MSG, FIX) __attribute__((deprecated(MSG, FIX)))
                                                 ^
1 error generated.