CMPLRLLVM-49853: Workaround debug build failure (#14876)
After 9f4dfcb795bb0ecf9944553f49371164801cd83f we start to get build
failure due to DEBUG in asan.

llvm/compiler-rt/lib/asan/asan_win.cpp(257,2): error: Please build the
runtime with a non-debug CRT: /MD or /M

This is to revert part of the changes in
9f4dfcb795bb0ecf9944553f49371164801cd83f to make debug builder happy.