Resolve of merge (conflict) b6979698ea5f Fix mlir windows buildbot after ec146cb7c0b4 'main' -> 'xmain-web' (#14123)
CONFLICT (content): Merge conflict in
llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp

  commit b6979698ea5f0c13ed4af661c88c981b9525e17c
  Author: Anna Thomas <anna@azul.com>
  Date:   Tue Jun 20 15:17:11 2023 -0400

      Fix mlir windows buildbot after ec146cb7c0b4

ec146cb7c0b4 added two new ReducKinds for float maximum and minimum
      (along with support in loop vectorizer).

Enumerate these kinds in SLPVectorizer to fix mlir windows build bot
      errors:


C:\buildbot\mlir-x64-windows-ninja\llvm-project\llvm\lib\Transforms\Vectorize\SLPVectorizer.cpp(13883):
error C2220: the following warning is treated as an error

C:\buildbot\mlir-x64-windows-ninja\llvm-project\llvm\lib\Transforms\Vectorize\SLPVectorizer.cpp(13883):
warning C4062: enumerator 'llvm::RecurKind::FMinimum' in switch of enum
'llvm::RecurKind' is not handled

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: sys_ce_bb <sys_ce_bb@intel.com>
Co-authored-by: Churina, Ksenia <ksenia.churina@intel.com>