Resolve of merge (conflict) 0c212e3fec4d Revert "[SYCL][UR] Link UR PI against UR Loader" (#8781) 'sycl' -> 'xmain-web' (1 commits) (#11888)
* Resolve of merge (conflict) 0c212e3fec4d Revert "[SYCL][UR] Link UR PI against UR Loader" (#8781) 'sycl' -> 'xmain-web' (1 commits)

  CONFLICT (content): Merge conflict in sycl/plugins/unified_runtime/CMakeLists.txt

  commit 0c212e3fec4d87edd6862aefc06e0f2ca6de04bc
  Author: Alexey Bader <alexey.bader@intel.com>
  Date:   Mon Mar 27 10:06:56 2023 -0700

      Revert "[SYCL][UR] Link UR PI against UR Loader" (#8781)

      Reverts intel/llvm#8637

      It caused at least 3 known regressions.

      1. https://github.com/intel/llvm/pull/8637#issuecomment-1482223287
      2.
      \sycl\plugins\unified_runtime\ur\adapters\level_zero\ur_level_zero_common.hpp(10):
      fatal error C1083: Cannot open include file: 'sycl/detail/pi.h': No such
      file or directory
      3. ld: error: undefined symbol: pthread_rwlock_wrlock (with GCC 7.5)

* conflict resolution

---------

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Manna, Soumi <soumi.manna@intel.com>