TreeTest.cpp - Add a comma to avoid build error with -werror
The macro `INSTANTIATE_TEST_CASE_P` is defined as
```
\# define INSTANTIATE_TEST_CASE_P(prefix, test_case_name, generator, ...) \
...
```

If we build the test case with -werror, we will get an error like
```
error: ISO C++11 requires at least one argument for the "..." in a
variadic macro

testing::ValuesIn(TestClangConfig::allConfigs()));
                                                ^
```
This patch fixes that.

Related Revision: https://reviews.llvm.org/D81388

Change-Id: I2da5c85e3398e7ceeb7415f42e0042ecb45f853e
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/253188
Reviewed-by: Kan ShengChen <shengchen.kan@intel.com>
Tested-by: Kan ShengChen <shengchen.kan@intel.com>