Resolve of merge (conflict) 455dce89e3f0 [SYCL] Improve error diagnostic for invalid SYCL kernel na.. '"sycl"' -> '"xmain-web"' (1 commits) (#1314)
* Resolve of merge (conflict) 455dce89e3f0 [SYCL] Improve error diagnostic for invalid SYCL kernel na.. '"sycl"' -> '"xmain-web"' (1 commits)

  CONFLICT (content): Merge conflict in clang/test/SemaSYCL/unnamed-kernel.cpp

  commit 455dce89e3f0bb9859d27552442436f9a76d08ed
  Author: smanna12 <soumi.manna@intel.com>
  Date:   Mon Nov 8 05:38:46 2021 -0500

      [SYCL] Improve error diagnostic for invalid SYCL kernel name (#4867)

      According to SYCL 2020 spec:
      The kernel name must be forward declarable at namespace scope (including global namespace scope) and may not be forward declared other than at namespace scope.

      The use of nested struct-case (where the name IS globally visible but just not forward-declarable) in a SYCL kernel name currently generates invalid error message:

      error: '{{.*}}' should be globally visible

      This patch modifies the error diagnostic message when the kernel name is declared at non-namespace scope (i.e. Inside a function or class/struct).

      Signed-off-by: Soumi Manna soumi.manna@intel.com

* Resolve conflict

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Maksim Sabianin <maksim.sabianin@intel.com>