Resolve of merge (conflict) ba49d39b20cc Use `<stdatomic.h>` with MSVC and C++ 'main' -> 'xmain-web' (#6348)
  CONFLICT (content): Merge conflict in clang/lib/Headers/stdatomic.h

  commit ba49d39b20cc5358da28af2ac82bd336028780bc
  Author: Igor Zhukov <fsb4000@yandex.ru>
  Date:   Mon Jul 25 18:54:32 2022 +0200

      Use `<stdatomic.h>` with MSVC and C++

      and use fallback only for C.

      It fixes the isssue with clang-cl:

      ```
      #include <stdatomic.h>
      #include <stdbool.h>
      #ifdef __cplusplus
      #include <atomic>
      using namespace std;
      #endif

      int main() {
          atomic_bool b = true;
      }
      ```

      ```
      $ clang-cl /TC main.cpp
      # works
      ```
      ```
      $ clang-cl /TP /std:c++20 main.cpp

      stdatomic.h(70,6): error: conflicting types for 'atomic_thread_fence'
      void atomic_thread_fence(memory_order);
           ^
      atomic(166,24): note: previous definition is here
      extern "C" inline void atomic_thread_fence(const memory_order _Order) noexcept {

      ...

      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      ```
      Many errors but
      `<stdatomic.h>` has many macros to built-in functions.
      ```
      #define atomic_thread_fence(order) __c11_atomic_thread_fence(order)
      ```
      and MSVC `<atomic>` has real functions.
      and the built-in functions are redefined.

      Reviewed By: #libc, aaron.ballman, Mordante

      Differential Revision: https://reviews.llvm.org/D130419

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Daniel Woodworth <daniel.woodworth@intel.com>