Fix build fail for lx_xmain_pgopti_xmainefi2linux
The fail reason is
```
error: unused variable [-Werror=unused-variable]
       int attemptedWidth = m_packetWidth;
```
attemptedWidth is only used for ouput in debug mode, so we wrap the code
with macro `#ifndef NDEBUG`, `#endif`

Change-Id: I00fca1c9fc0b9726f603566b608566aeb79075a6
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/253122
Reviewed-by: Kan ShengChen <shengchen.kan@intel.com>
Tested-by: Kan ShengChen <shengchen.kan@intel.com>