Interim fix to resolve self-build after 1d13f84 [SYCL] Fix segmentation fault that occurs when creating host accessors in parallel (#1597).
Issue: error: undefined reference to 'pthread_rwlock_trywrlock'.
This is a temporary fix, to expliciytly use pthread, instead of relying on find_package(Threads)
on non MSVC environments.

Dmitry is requested to provide a proper fix.

Change-Id: Ice611c716cbda94056b653b5b672e021b62f8913
Reviewed-on: https://git-amr-2.devtools.intel.com/gerrit/246734
Reviewed-by: Gaba, Abhinav <abhinav.gaba@intel.com>
Tested-by: Gaba, Abhinav <abhinav.gaba@intel.com>