Resolve of merge (conflict) edaae251cca0 [clang] better error message for while loops outside of co.. 'main' -> 'xmain-web' (#6341)
  CONFLICT (content): Merge conflict in clang/lib/Parse/ParseDecl.cpp

  commit edaae251cca07c34c55905c424a8f677623d0bd0
  Author: inclyc <me@inclyc.cn>
  Date:   Wed Jul 13 00:12:12 2022 +0800

      [clang] better error message for while loops outside of control flow

      report an error when encountering 'while' token parsing declarator

      ```
      clang/test/Parser/while-loop-outside-function.c:3:1: error: while loop outside of a function
      while // expected-error {{while loop outside of a function}}
      ^
      clang/test/Parser/while-loop-outside-function.c:7:1: error: while loop outside of a function
      while // expected-error {{while loop outside of a function}}
      ^
      ```

      Fixes: https://github.com/llvm/llvm-project/issues/34462

      Differential Revision: https://reviews.llvm.org/D129573

Co-authored-by: iclsrc <ia.compiler.tools.git@intel.com>
Co-authored-by: Daniel Woodworth <daniel.woodworth@intel.com>